### ISSUE TITLE
Meta issue: Improvements for metrics packages and helpers

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-sdk#2811]
There have been several bug reports, feature requests, and questions posted recently that bring into focus the fact that the SDK packages and helper functions for generating metrics are in need of some attention.

So far the major themes I've seen are:
- [ ] Need to have clear delineation between when the operator namespace is required vs when the watch namespaces are required.
- [x] Need to support generating metrics for cluster-scoped CRDs (see #2809) 
- [ ] Need to support generating metrics across all namespaces for namespace-scoped GVKs when `WATCH_NAMESPACE=""`
- [ ] Need to have better documentation and UX around telling the kube-state-metrics generators which GVKs to generate metrics for (see #2798)

/cc @raffaelespazzoli @akoserwal @camilamacedo86

**Comment by joelanford** [comment]
We're going to re-evaluate this after the switch to kubebuilder scaffolding, since we need to upstream kube-state-metrics support to bring these features to the new Kubebuilder-style scaffolding.

**Comment by camilamacedo86** [comment]
Hi @joelanford, 

May we need to add more one item here which is:

Allow the scenario where we set WATCH-NAMESPACE=A and then, deploy the operator in B and the service monitor would be created successfully in B beside B not be passed to the [manager](https://github.com/operator-framework/operator-sdk-samples/blob/9bb42cdb16f5b25e4e77297e9c906dbd5e6b9c44/go/memcached-operator/cmd/manager/main.go#L97). The suggested solution made by @shawn-hurley would be `use the direct write and read client` instead of the cache. However, we would still require permissions to list and create services in the operator namespace.

**Comment by joelanford** [comment]
We think this is more-or-less solved by the new [`InstrumentedEnqueueRequestForObject`](https://github.com/operator-framework/operator-sdk/blob/master/pkg/handler/instrumented_enqueue_object.go) handler.

This handler is now being used by default in the Helm and Ansible operators, and it will be available in [`operator-lib`](https://github.com/operator-framework/operator-lib/) to be used (opt-in) by Go operators.

@jmrodri Can you close this issue when this handler is available in `operator-lib`?

**Comment by joelanford** [comment]
This is complete. See https://pkg.go.dev/github.com/operator-framework/operator-lib@v0.0.0-20200725025138-9db1e01252e9/handler?tab=doc#InstrumentedEnqueueRequestForObject
