### ISSUE TITLE
Operator SDK 1.0 Meta-issue

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-sdk#3327]
The Operator SDK maintainers and community members have been hard at work adding new features to improve integration with the [Operator Lifecycle Manager](https://github.com/operator-framework/operator-lifecycle-manager) and to unify project structures with [Kubebuilder](https://github.com/kubernetes-sigs/kubebuilder).

Many of these features are already on `master`, but some are still outstanding. The purpose of this issue is to communicate with the community about what the proposed 1.0 feature set is, and to document what's in, what's out, and what major changes we plan to make for existing projects.

Support for legacy project layouts (scaffolded with the `new` subcommand) will be removed for 1.0. The latest pre-1.0 release will receive patch updates to give users time to migrate to the new project structure. No new features will be backported from 1.0 to the latest pre-1.0 release.

**1.0.0 GA**
- [x] Should display the commit info - https://bugzilla.redhat.com/show_bug.cgi?id=1865808 (#3643) NOTE: @jmrodri to add a note in release for this tomorrow
- [x] Simplify `operator-sdk cleanup` command (#3644)
- [x] Fix molecule scaffolding error (https://github.com/operator-framework/operator-sdk/pull/3654)
- [x] Docs: reference to old boilerplate code Issue #3460 - PR #3543 
- [x] Migration guide for Ansible : https://github.com/operator-framework/operator-sdk/pull/3571
- [x] Molecule scaffolding fixes: https://github.com/operator-framework/operator-sdk/pull/3661

**1.0.0-alpha.2**
- [x] remove --operator-name flag from generate subcommands (#3530)
- [x] switch to controller runtime log flags for helm and ansible and remove `internal/log` (#3596)
- [x] helm/ansible subcommands (#3596)
- [x] move scorecard APIs to `operator-framework/api` and remove `pkg/apis` (https://github.com/operator-framework/api/pull/55) (#3622)
- [x] Remove default channel validation from bundle lib (from [operator-registry PR #408](https://github.com/operator-framework/operator-registry/pull/408)) (#3602)
- [x] Update `run packagemanifests` flags 
  - Remove `--include` and `--olm-namespace` flags (#3599, #3601)
  - Rename `--operator-version` to `--version` (#3599)
  - Rename `--operator-namespace` to `--namespace` (#3601)
- [x] Fix CSV generation related to roles, role bindings, service accounts. (#3610)

**What's added in `v1.0.0`**

- [x] `operator-sdk generate kustomize manifests`
- [x] `operator-sdk generate bundle`
- [x] `operator-sdk generate packagemanifests`
- [x] `operator-sdk <run|cleanup> packagemanifests`
- [x] Go project scaffolding using the Kubebuilder project layout
- [x] Helm project scaffolding using the Kubebuilder project layout (#3421)
- [x] `operator-sdk scorecard` will be updated with the new scorecard implementation, currently under `operator-sdk alpha scorecard` (#3444)
- [x] `operator-sdk scorecard` will support both sequential and parallel stages (#3434)
- [x] New controller-runtime handler that generates kube-state-metrics metrics (and incorporate into helm and ansible operators). (#3436)
- [x] Rewrite e2e tests to handle new helm operator scaffolding (#3421)
- [x] Use controller-runtime leader election in helm-operator (#3446)
- [x] Helm/ansible operators: rename `--max-workers` to `--max-concurrent-reconciles` (#3452, #3456)
- [x] Ansible: rename `WORKER_%s_%s` envvar to `MAX_CONCURRENT_RECONCILES_%s_%s` (#3435)
- [x] Split importable SDK library components into a separate (non 1.0) repository. (#3503)
- [x] Move `pkg/log/zap` to `internal/log/zap` (#3525)
- [x] Support custom scorecard config.yaml path in metadata/annotations.yaml (#3474)
- [x] Use controller-runtime leader election in ansible-operator (#3457)
- [x] remove runlocal stuff from  `leader.Become` in operator-lib (https://github.com/operator-framework/operator-lib/pull/7)
- [x] update `handler/enqueue_annotation.go` with changes from https://github.com/kubernetes-sigs/controller-runtime/pull/892 (https://github.com/operator-framework/operator-lib/pull/2)
- [x] update operator-sdk to point to https://operator-framework/operator-lib for ansible/helm
- [x] delete `pkg/handler/enqueue_annotation.go` from operator-sdk; have ansible to use `operator-framework/operator-lib/handler` instead (#3506)
- [x] delete `pkg/handler/instrumented` from operator-sdk; have ansible/helm use `operator-framework/operator-lib/handler` instead (#3523)
- [x] switch ansible-operator to use operator-lib/predicate (#3481)
- [x] switch helm-operator to use operator-lib/predicate (#3481)
- [x] Remove `GenerationChangedPredicate` from `predicate`. Moved `pkg/predicate` to `pkg/ansible/predicate` (~#3491~ #3532)
- [x] move jmrodri/operator-lib to [operator-framework/operator-lib](https://github.com/operator-framework/operator-lib)
- [x] setup [github actions](https://github.com/joelanford/helm-operator/blob/master/.github/workflows/ci.yml) on operator-framework/operator-lib ([actions tab](https://github.com/operator-framework/operator-lib/actions))
- [x] update go docs of code in operator-lib (NICE TO HAVE) (https://github.com/operator-framework/operator-lib/pull/16)
- [x] Fix CVE-2020-14040 from golang.org/x/text [Bug 1855608](https://bugzilla.redhat.com/show_bug.cgi?id=1855608) (#3458)
- [x] Allow `.yml` changelog fragments (#3493)
- [x] Move `InstrumentedEnqueueRequestForObject` to operator-lib (https://github.com/operator-framework/operator-lib/pull/8)
- [x] add license check to operator-lib (https://github.com/operator-framework/operator-lib/pull/14)
- [x] Move existing quickstarts to "tutorial" or "user guide" (name TBD), and author _actual_ quickstart docs for Go, Ansible, and Helm operators. (PR done for Go #3551 -  Helm #3552 - Ansible #3555
- [x] Increase test coverage for operator-lib (https://github.com/operator-framework/operator-lib/pull/15)
- [x] Update `go.mod` requires to use tagged versions of operator-lib and controller-runtime (#3616)
- [x] Bump controller-runtime to v0.6.2 (https://github.com/kubernetes-sigs/kubebuilder/pull/1625, #3653)
- [x] Add scorecard e2e test (#3507)
- [x] Ensure `operator-sdk` repository has no exported public Go APIs.
- [x] tag operator-framework/operator-lib (https://github.com/operator-framework/operator-lib/releases/tag/v0.1.0)

**What's removed in `v1.0.0`**

- [x] `operator-sdk exec-entrypoint` (#3331)
- [x] `operator-sdk build` (#3566)
- [x] `operator-sdk add api` for Go operators (#3385)
- [x] `operator-sdk add controller` (#3385)
- [x] `operator-sdk add crd` for Go operators (#3547)
- [x] `operator-sdk migrate` (#3385)
- [x] `operator-sdk print-deps` (#3385)
- [x] `operator-sdk generate k8s` (#3385)
- [x] `operator-sdk generate crds` (#3385)
- [x] The legacy scorecard implementation is being removed (replaced by new scorecard implementation). (#3385)
- [x] The `operator-sdk test` subcommand and e2e framework are being removed. Users should migrate to `envtest`. (#3409)
- [x] `operator-sdk run local`. To continue supporting running helm and ansible operators locally, we will release these binaries so that upcoming `make run` targets for those operator types can download and run the operator binaries locally. (#3406)
- [x] `operator-sdk cleanup` for legacy projects. (#3406)
- [x] Legacy `run packagemanifests` support (#3406)
- [x] Legacy `generate csv` (#3414)
- [x] Legacy `generate bundle` (#3414)
- [x] Legacy `generate packagemanifests`(#3414)
- [x] Legacy `operator-sdk bundle <create/validate>` is removed. (#3414)
- [x] Remove `test/test-framework` sample project that is used for legacy tests (#3424)
- [x] Remove legacy docs and examples (#3432)
- [x] Remove scaffolding for legacy helm operators (#3343)
- [x] `operator-sdk [new|add api]` CLI for Helm operators  (#3343)
- [x] Remove creation of service, service monitor, and kube-state-metrics server from Helm operator (#3451)
- [x] Remove creation of service, service monitor, and kube-state-metrics server from Ansible operator (#3466)
- [x] `pkg/metrics` and `pkg/kube-metrics`
- [x] Ansible operator remove unused `WATCH_NAMESPACE` and `POD_NAME` environment variables from manager template (#3570)

**Checklist for 1.0.0-alpha1 release**

- [x] New CSV marker format for Go APIs (#2792)
- [x] Ansible project scaffolding using the Kubebuilder project layout (#3488)
- [x] Rewrite e2e tests to handle new ansible operator scaffolding (#3488)
- [x] Remove `operator-sdk [new|add api]` CLI for Ansible operators (#3531)
- [x] Remove scaffolding for legacy ansible operators (#3531)
- [x] `operator-sdk scorecard` config file is a [componentconfig](https://docs.google.com/document/d/1FdaEJUEh091qf5B98HM6_8MS764iXrxxigNIdwHYW9c/edit) (#3490)
- [x] Scaffold a scorecard config.yaml file (#3490)
- [x] Bump kubebuilder version in Operator SDK repo (#3438)
- [x] Move `pkg/helm` to `internal/helm` (#3537) 
- [x] Move `pkg/ansible` to `internal/ansible` (#3560)
- [x] Use consistent domain everywhere (*.sdk.operatorframework.io) (#3527)
- [x] Ansible operator should use default metrics addr in `manager.yaml` (#3570)
- [x] Helm and Ansible operators should support OLM manifest generation (#3341)
- [x] Wordsmith release notes for alpha1 release. Generated  [CHANGELOG.md](https://github.com/jmrodri/operator-sdk/blob/changelog-wordsmith-review/CHANGELOG.md) & [migration guide](https://github.com/jmrodri/operator-sdk/blob/changelog-wordsmith-review/website/content/en/docs/upgrading-sdk-version/v1.0.0.md#new-and-api-subcommands-are-no-longer-supported-for-helm-based-operators) (#3544)

**Comment by estroz** [comment]
For anyone interested, this PR adds a migration tool to migrate a legacy project to a new one: #2851.

**Comment by camilamacedo86** [comment]
The above ones are important for: 
- Allows OLM subcommands work for Helm/Ansible new layout #3341 (otherwise OLM subcommands cannot work for Ansible/Helm)
- doc: Fix/Update the migration guide with the steps required to migrate the Memcached sample #3543 (otherwise, users cannot migrate their projects for the new layout)
- removal: support to the legacy projects #3539 (we have many tasks related to removals but this one remove all legacy support and what is missing )


c/c @jmrodri @joelanford

**Comment by camilamacedo86** [comment]
- Allows OLM subcommands work for Helm/Ansible new layout #3341
- removal: support to the legacy projects #3539 


c/c @jmrodri @joelanford

**Comment by xiangjingli** [comment]
@joelanford  Can I get the ETA of the operator SDK V1.0? Thanks!

**Comment by joelanford** [comment]
@xiangjingli Current plan is mid-next week, barring any unforeseen issues that arise between now and then.

**Comment by joelanford** [comment]
1.0 was released a few weeks ago. Closing this out.
