### ISSUE TITLE
Implement `run bundle` subcommand to improve OLM integration

### ISSUE THREAD

**Issue by jmrodri** [operator-framework/operator-sdk#3626]
The Operator SDK maintainers are hard at work to implement `run bundle` to improve integration with the [Operator Lifecycle Manager](https://github.com/operator-framework/operator-lifecycle-manager). 

The purpose of this issue is to communicate with the community what will be in `run bundle`. 

**TODO**
- [x] create registry image pod (#3337 , #3665 )
- [x] ~~rebase / update [operator-group-install-mode branch](https://github.com/jmrodri/operator-sdk/tree/operator-group-install-mode)~~
- [x] scaffold out structs from diagram to start (#3636)
- [x] implement Config struct, refer to [kubectl operator plugin](https://github.com/operator-framework/kubectl-operator/blob/b8911eec586a2274c07eeeb20b8b15b5ebea76f5/internal/cmd/root.go#L26-L28) and cobra "prerun" (#3636)
- [x] implement RunBundle and tie CLI to call OperatorInstaller (#3636)
- [x] connect `run bundle` to the Operator SDK CLI (#3636)
- [x] create grpc catalogsource (#3467, #3832 )
- [x] implement OperatorInstaller (#3764, #3838)
- [x] implement IndexImageCatalogCreator (create CatalogCreator interface) (#3467)
- [x] implement PackageManifestCatalogCreator (maybe) (#3764)
- [x] update OperatorGroup logic to handle install mode for `run bundle` (#3861)
- [x] create Subscription logic (#3764, #3838)
- [x] verify operator is installed/upgraded (~~#3766~~ #3819)
- [ ] write e2e test for `run bundle` and enable run bundle CLI (~~#3844~~ #3831)

Reference information
* [run bundle enhancement](https://github.com/operator-framework/enhancements/blob/master/enhancements/run-bundle.md) which describes the CLI to be implemented
* [run bundle upgrade enhancement](https://github.com/operator-framework/enhancements/blob/master/enhancements/run-bundle-upgrade.md)
* [kubectl operator plugin](https://github.com/joelanford/kubectl-operator)

Proposed design:
![operator-sdk-run-subcommand](https://user-images.githubusercontent.com/17137/89105654-f852a900-d3f0-11ea-84fd-ddf43c600b5a.png)

**Comment by jmrodri** [comment]
`run bundle` is now in the operator-sdk.
