### ISSUE TITLE
 Meta-issue:  Implement `run bundle upgrade` subcommand to improve OLM integration

### ISSUE THREAD

**Issue by rashmigottipati** [operator-framework/operator-sdk#4176]
The Operator SDK maintainers are hard at work to implement run bundle upgrade to improve integration with the Operator Lifecycle Manager. 

The goal of run bundle upgrade subcommand is to make Operator Developers rely on the Operator SDK to facilitate an upgrade of an Operator from its previous version, using Operator Lifecycle Manager.
Ideally, this command automates a lot of the manual orchestration typically required to upgrade an operator from one version to another. 

The purpose of this issue is to communicate with the community what will be in `run bundle upgrade` subcommand.

**TODO**

- [x] investigate and refactor registry pod for operator upgrade (#4271) 

- [x] add new annotations/modify existing annotations in catalog source suitable for operator upgrade (#4271)

- [x] update catalog source with address and annotations for operator upgrade (#4271)

- [x] approve the install plan for performing operator upgrade (#4271)

- [x] implement `run bundle upgrade` CLI (#4271)

- [x] connect `run bundle upgrade` to the Operator SDK CLI (#4271)

- [ ] verify operator upgrade is successful (follow-up PR)

- [ ] write unit & e2e tests for run bundle upgrade (follow-up PR)

**References**

- [run bundle upgrade enhancement](https://github.com/operator-framework/enhancements/blob/master/enhancements/run-bundle-upgrade.md)

**Comment by rashmigottipati** [comment]
`run bundle-upgrade` is now a part of operator-sdk
