### ISSUE TITLE
[META] Scorecard Enhacements Tracker

### ISSUE THREAD

**Issue by theishshah** [operator-framework/operator-sdk#5339]
This ticket is to track suggested improvements and bug-fixes to the scorecard. If an item is be explored, a new issue should be created and linked back here.

- [ ]  Disconnected environment scorecard images
- [ ]  Additional fields to track optional junit/xunit types
- [ ]  Support more/total environment configuration in SC config (eg. ServiceAccount)
- [ ]  Split scorecard run/environment configurations

**Comment by jmccormick2001** [comment]
long term you will want to consider moving out scorecard tests from the basic/olm suites that might be better implemented as static validations that the SDK validation can perform, that way it would focus scorecard on functional tests...something to consider long term, the pipelines already call the sdk's validate command as well to perform various static checks.

**Comment by jmccormick2001** [comment]
you might also debate just splitting out the scorecard into its own repo, and then create a kubectl-like plugin to invoke scorecard from the sdk binary, another long term thing to consider doing.
