### ISSUE TITLE
Meta-issue: digest based bundle

### ISSUE THREAD

**Issue by jmrodri** [operator-framework/operator-sdk#5511]
#### Describe the problem you need a feature to resolve.
Package Operator bundles in a way that runs well on clusters in a restricted network and/or production environment with OLM.

- [ ] Address EP comments [PR #107](https://github.com/operator-framework/enhancements/pull/107)
- [ ] Work on makefile changes
- [ ] Work on implementation....

**Comment by jberkhahn** [comment]
this has been handled, so closing this meta issue
