### ISSUE TITLE
Add File-Based Catalog (FBC) support to run bundle and run bundle-upgrade commands

### ISSUE THREAD

**Issue by rashmigottipati** [operator-framework/operator-sdk#5593]
#### Describe the problem you need a feature to resolve.

One of the main goals of the Operator SDK is to enable operator developers to install and run their operators using Operator Lifecycle Manager (OLM). Currently, there are two commands in the SDK for installing an operator bundle (run bundle) and upgrading an operator bundle to a newer version (run bundle-upgrade) using OLM. Operator SDK installs and upgrades the operator bundles using opm tooling that inherently uses a SQLite database under the hood, which is responsible for generating the registry database as well as the index images. We use `opm registry add` command under the hood to create an ephemeral index image during the run bundle(-upgrade) workflow; however, that command is being deprecated. 

As OLM is transitioned to declarative config which is a more human readable and consumable format of a catalog that is in the form of JSON/YAML, Operator SDK should also transition the existing run bundle(-upgrade) commands to support declarative config index images and default to using file based catalogs so that Operator authors can continue using Operator SDK to install/upgrade their operator bundles using the new FBC format. These commands are also being used by the pipeline teams, e.g. in CVP, so we need to enable FBC support for these two commands and ensure they work well with file-based catalogs. 

#### Describe the solution you'd like.

We need to be able to build a declarative config on the fly when run bundle is invoked. Previously, we used `opm registry add` command to create the ephemeral index image. That would have to be modified/replaced with `opm render` command or the equivalent of it by leveraging the Operator Registry APIs. The declarative config should then be served using `opm serve` command over a gRPC port during creation of the registry pod container. More details are discussed in [Draft EP for run bundle](https://docs.google.com/document/d/18_HEbVpdSNY8lQn6Epn634bInHdfgS14ANiB7LNI_Dw/edit).

POC links: 
- [feature branch that's being actively worked on](https://github.com/operator-framework/operator-sdk/tree/feature/run-bundle) - feature branch that has all of the run bundle(-upgrade) work
- [run bundle prototype](https://github.com/rashmigottipati/operator-sdk/tree/run-bundle-prototype) - make run bundle work with FBC support, without using source index image, by generating a minimal FBC and serving the FBC over a gRPC port during registry pod creation. 
- [run bundle-upgrade prototype](https://github.com/VenkatRamaraju/operator-sdk/tree/run-bundle-upgrade-prototype) - handle operator bundle upgrade when an operator bundle was installed using `run bundle` command and also installed traditionally via OLM by creating a `CatalogSource` and `Subscription`.

**TODO**

- [x] [Draft EP for run bundle](https://docs.google.com/document/d/18_HEbVpdSNY8lQn6Epn634bInHdfgS14ANiB7LNI_Dw/edit) 

- [x] [Design proposal to add FBC support to run bundle](https://github.com/operator-framework/enhancements/pull/112)

- [x] [Implement File-Based Catalog support to run bundle](https://github.com/operator-framework/operator-sdk/pull/5671)

- [x] [Implement File-Based Catalog support to run bundle-upgrade command](https://github.com/operator-framework/operator-sdk/pull/5769)

- [ ] Merge feature branch into master

Would love to get some feedback/inputs on this.
