### ISSUE TITLE
meta issue for k8s 1.24 bump

### ISSUE THREAD

**Issue by everettraven** [operator-framework/operator-sdk#5820]
## Meta Issue for k8s 1.24 bump
In order to bump Operator SDK to support Kubernetes 1.24 there are a few dependencies we rely on making the bump first. 

This issue is meant to help track all dependencies and the status of their bumps.

### Order of dependency bumps
**Step 1: upgrade controller-runtime, controller-tools, helm, and operator-framework/operator-manifest-tools(can be done in parallel)**
- [x] sigs.k8s.io/controller-runtime (v0.12.1 supports k8s 1.24, PR: https://github.com/kubernetes-sigs/controller-runtime/pull/1885)
- [x] sigs.k8s.io/controller-tools (v0.9.0 supports k8s 1.24, PR: https://github.com/kubernetes-sigs/controller-tools/pull/669)
- [x] operator-framework/operator-manifest-tools (PR: https://github.com/operator-framework/operator-manifest-tools/pull/26)
- [x] helm.sh/helm/v3 (3.9.0 supports k8s 1.24, commit: https://github.com/helm/helm/commit/bd7c97f786f59b993dc34884f3d44ca0297f13e8)

**Step 2: upgrade operator-framework/api and sigs.k8s.io/kubebuilder-declarative-pattern (can be done immediately after controller-runtime)**
- [x] operator-framework/api (0.15.0 supports k8s 1.24, PR: https://github.com/operator-framework/api/pull/242) 
- [x] sigs.k8s.io/kubebuilder-declarative-pattern (PR: https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/217)

**Step 3.1: upgrade operator-framework/operator-registry and operator-framework/operator-lib (can be done immediately after operator-framework/api)**
- [x] operator-framework/operator-registry (PR: https://github.com/operator-framework/operator-registry/pull/964)
- [x] operator-framework/operator-lib (0.11.0 supports k8s 1.24, PR: https://github.com/operator-framework/operator-lib/pull/108)

**Step 3.2: upgrade kubebuilder (blocked until kubebuilder-declarative-pattern is bumped)**
- [x] sigs.k8s.io/kubebuilder/v3 (PR in progress: https://github.com/kubernetes-sigs/kubebuilder/pull/2679)

**Step 4: upgrade operator-framework/helm-operator-plugins and operator-framework/java-operator-plugins**
- [x] operator-framework/helm-operator-plugins (v0.0.11 supports k8s 1.24, PR: https://github.com/operator-framework/helm-operator-plugins/pull/174)
- [x] operator-framework/java-operator-plugins (v0.5.0  uses 1.24 kubebuilder https://github.com/operator-framework/java-operator-plugins/pull/88)

**Step 5:  upgrade operator-framework/operator-sdk dependencies**
- [x] Bump SDK to use k8s 1.24 (PR in progress: https://github.com/operator-framework/operator-sdk/pull/5843)
- [x] Bump envtest to 1.24 (PR: https://github.com/operator-framework/operator-sdk/pull/5835)

**Comment by everettraven** [comment]
All actions are completed to allow Operator SDK to support k8s 1.24. Closing.
