### ISSUE TITLE
Meta Issue for K8S 1.25 & golang 1.19 Bump

### ISSUE THREAD

**Issue by theishshah** [operator-framework/operator-sdk#5937]
## Meta Issue for k8s 1.25 bump & golang 1.19
In order to bump Operator SDK to support Kubernetes 1.25 there are a few dependencies we rely on making the bump first. 

This issue is meant to help track all dependencies and the status of their bumps.

### Order of dependency bumps
**Step 1: upgrade controller-runtime, controller-tools, helm, and operator-framework/operator-manifest-tools(can be done in parallel)**
- [x] sigs.k8s.io/controller-runtime https://github.com/kubernetes-sigs/controller-runtime/pull/1985
- [x] sigs.k8s.io/controller-tools  https://github.com/kubernetes-sigs/controller-tools/pull/717
- [x] operator-framework/operator-manifest-tools https://github.com/operator-framework/operator-manifest-tools/pull/28

**Step 2: upgrade operator-framework/api and sigs.k8s.io/kubebuilder-declarative-pattern (can be done immediately after controller-runtime)**
- [x] operator-framework/api  https://github.com/operator-framework/api/pull/260
- [x] sigs.k8s.io/kubebuilder-declarative-pattern https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/238

**Step 3.1: upgrade operator-framework/operator-registry and operator-framework/operator-lib (can be done immediately after operator-framework/api)**
- [x] operator-framework/operator-registry https://github.com/operator-framework/operator-registry/pull/1024
- [x] operator-framework/operator-lib https://github.com/operator-framework/operator-lib/pull/109

**Step 3.2: upgrade kubebuilder (blocked until kubebuilder-declarative-pattern is bumped)**
- [x] sigs.k8s.io/kubebuilder/v3 

**Step 4: upgrade operator-framework/helm-operator-plugins and operator-framework/java-operator-plugins**
- [x] operator-framework/helm-operator-plugins https://github.com/operator-framework/helm-operator-plugins/pull/200
- [x] operator-framework/java-operator-plugins https://github.com/operator-framework/java-operator-plugins/pull/103

**Step 5:  upgrade operator-framework/operator-sdk dependencies**
- [x] Bump Ginkgo/v2 and Kubebuilder 1.25 https://github.com/operator-framework/operator-sdk/pull/6047
- [x] Bump SDK to use k8s 1.25 https://github.com/operator-framework/operator-sdk/pull/6044
- [x] Bump envtest to 1.25 https://github.com/operator-framework/operator-sdk/pull/6088

**Comment by jmrodri** [comment]
So we need to add a space in between each of the `[]` so that they show up as boxes. And I assume the k8s versions should be 1.25 instead of 1.24 :)

**Comment by varshaprasad96** [comment]
Nit: We need not bump `helm.sh/helm/v3` to the latest k8s version. Their release cadence is way different (usually super slow). We just need to bump  the helm dependency in plugins to the latest `helm-v3` version which is built with a compatible k8s.

**Comment by laxmikantbpandhare** [comment]
I created an issue on controller-tools to track the v1.25.0 bump Issue - https://github.com/kubernetes-sigs/controller-tools/issues/707

As of now, we are planning to bump it to v1.25.0-alpha.3 - I raised PR https://github.com/kubernetes-sigs/controller-tools/pull/708

**Comment by laxmikantbpandhare** [comment]
Updated `controller-tools` to `v1.25.0-alpha.3`

**Comment by laxmikantbpandhare** [comment]
I created an issue on controller-tools to track the v1.25 bump issue - https://github.com/kubernetes-sigs/controller-tools/issues/711

**Comment by laxmikantbpandhare** [comment]
Raised PR on controller-tools - https://github.com/kubernetes-sigs/controller-tools/pull/717

Maybe we need to wait for a bump of golang version to 1.19

**Comment by laxmikantbpandhare** [comment]
'operator-manifest-tool' k8s 1.25 bump completed.

**Comment by everettraven** [comment]
Kubebuilder-declarative-pattern is done as of https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/238

**Comment by laxmikantbpandhare** [comment]
`operator-framework/api` bump k8s 1.25 merged https://github.com/operator-framework/api/pull/260

**Comment by varshaprasad96** [comment]
@theishshah Can we make sure that https://github.com/operator-framework/operator-sdk/issues/6037 is in.

**Comment by asmacdo** [comment]
We need to add https://github.com/operator-framework/operator-sdk/issues/6031

**Comment by laxmikantbpandhare** [comment]
Did java-operator-plugins release [v0.7.0 ](https://github.com/operator-framework/java-operator-plugins/releases/tag/v0.7.0)
It will fix #6031 and it will be added in `operator-sdk` next release `v1.24.0`.

**Comment by laxmikantbpandhare** [comment]
All k8s 1.25 updates completed for this issue.
