### ISSUE TITLE
Meta Issue for K8S 1.26

### ISSUE THREAD

**Issue by jmrodri** [operator-framework/operator-sdk#6128]
## Meta Issue for k8s 1.26 bump
In order to bump Operator SDK to support Kubernetes 1.25 there are a few dependencies we rely on making the bump first. 

This issue is meant to help track all dependencies and the status of their bumps.

### Order of dependency bumps
**Step 1: upgrade controller-runtime, controller-tools, helm, and operator-framework/operator-manifest-tools(can be done in parallel)**
- [x] sigs.k8s.io/controller-runtime - https://github.com/kubernetes-sigs/controller-runtime/pull/2087 - Included in release v0.14.0
- [x] sigs.k8s.io/controller-tools - https://github.com/kubernetes-sigs/controller-tools/pull/749 - Included in release v0.11.0
- [ ] operator-framework/operator-manifest-tools

**Step 2: upgrade operator-framework/api and sigs.k8s.io/kubebuilder-declarative-pattern (can be done immediately after controller-runtime)**
- [ ] operator-framework/api
- [x] sigs.k8s.io/kubebuilder-declarative-pattern - https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/291

**Step 3.1: upgrade operator-framework/operator-registry and operator-framework/operator-lib (can be done immediately after operator-framework/api)**
- [ ] operator-framework/operator-registry
- [ ] operator-framework/operator-lib

**Step 3.2: upgrade kubebuilder (blocked until kubebuilder-declarative-pattern is bumped)**
- [x] sigs.k8s.io/kubebuilder/v3 - https://github.com/kubernetes-sigs/kubebuilder/pull/3147 - Included in v3.9.0 release

**Step 4: upgrade operator-framework/helm-operator-plugins and operator-framework/java-operator-plugins**
- [ ] operator-framework/helm-operator-plugins - https://github.com/operator-framework/helm-operator-plugins/pull/211
- [x] operator-framework/java-operator-plugins - https://github.com/operator-framework/java-operator-plugins/pull/112

**Step 5:  upgrade operator-framework/operator-sdk dependencies**
- [ ] Bump Ginkgo/v2 and Kubebuilder 1.26
- [ ] Bump SDK to use k8s 1.26
- [ ] Bump envtest to 1.26

**Comment by varshaprasad96** [comment]
(not related just side note) If there aren't any breaking changes from one k8s version to another, I wish we could automate this process :/

**Comment by jberkhahn** [comment]
see #5937

**Comment by rashmigottipati** [comment]
SDK bump PR to upgrade k8s dependencies to 1.26: https://github.com/operator-framework/operator-sdk/pull/6352

**Comment by everettraven** [comment]
Closing as Kubernetes 1.26 support has been shipped with the v1.28.0 release. Thanks to everyone for their help in getting this delivered!
