### ISSUE TITLE
Meta Issue for K8S 1.27

### ISSUE THREAD

**Issue by oceanc80** [operator-framework/operator-sdk#6381]
## Meta Issue for k8s 1.27 bump
In order to bump Operator SDK to support Kubernetes 1.27 there are a few dependencies we rely on making the bump first. 

This issue is meant to help track all dependencies and the status of their bumps.

### Order of dependency bumps
**Step 1: upgrade controller-runtime, controller-tools, helm, and operator-framework/operator-manifest-tools(can be done in parallel)**
- [x] sigs.k8s.io/controller-runtime 
- [x] sigs.k8s.io/controller-tools 
- [x] operator-framework/operator-manifest-tools

**Step 2: upgrade operator-framework/api and sigs.k8s.io/kubebuilder-declarative-pattern (can be done immediately after controller-runtime)**
- [x] operator-framework/api
- [x] sigs.k8s.io/kubebuilder-declarative-pattern 

**Step 3.1: upgrade operator-framework/operator-registry and operator-framework/operator-lib (can be done immediately after operator-framework/api)**
- [x] operator-framework/operator-registry https://github.com/operator-framework/operator-registry/pull/1120
- [x] operator-framework/operator-lib

**Step 3.2: upgrade kubebuilder (blocked until kubebuilder-declarative-pattern is bumped)**
- [x] sigs.k8s.io/kubebuilder/v3 

**Step 4: upgrade operator-framework/helm-operator-plugins and operator-framework/java-operator-plugins**
- [x] operator-framework/helm-operator-plugins https://github.com/operator-framework/helm-operator-plugins/pull/216
- [x] operator-framework/java-operator-plugins https://github.com/operator-framework/java-operator-plugins/pull/119

**Step 5:  upgrade operator-framework/operator-sdk dependencies**
- [x] Bump Ginkgo/v2 and Kubebuilder 1.27
- [ ] Bump SDK to use k8s 1.27
- [ ] Bump envtest to 1.27

**Comment by acornett21** [comment]
@varshaprasad96 @everettraven Just wanted to let you all know that I started raising PR's for this issue. I'll be out next week, so I won't be at any of the community meetings, but thought you all might want a heads up on this and could help push a few of the PR's along.

**Comment by varshaprasad96** [comment]
Current releases that have k8s updates:
1. Controller-runtime: https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.15.0
2. Controller-tools: https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.12.0
3. Kubebuilder: https://github.com/kubernetes-sigs/kubebuilder/releases/tag/v3.11.0

These three release versions need to updated in plugins.

**Comment by Neo2308** [comment]
The PR for operator-framework/operator-registry (Step 3.1 (a)) seems to be merged. Is there anything pending there?
PR: https://github.com/operator-framework/operator-registry/pull/1120/files

The PR for operator-framework/helm-operator-plugins (Step 4 (a)) also seems to be merged. Is there anything pending there?
PR: https://github.com/operator-framework/helm-operator-plugins/pull/216

If both of these are done, are we good to move on to step 5?

**Comment by varshaprasad96** [comment]
https://github.com/operator-framework/operator-sdk/pull/6514 --> would update k8s in SDK alongside the all the plugins.

**Comment by acornett21** [comment]
@everettraven Are the bottom two tasks complete as well? Just want to make sure we aren't missing anything.

**Comment by everettraven** [comment]
@acornett21 I believe so. They should have been taken care of as part of #6613 . I just checked the boxes off, thanks for the reminder :)
