### ISSUE TITLE
Meta Issue for k8s 1.30 bump

### ISSUE THREAD

**Issue by Neo2308** [operator-framework/operator-sdk#6730]
Meta Issue for k8s 1.30 bump

In order to bump Operator SDK to support Kubernetes 1.30 there are a few dependencies we rely on making the bump first.
This issue is meant to help track all dependencies and the status of their bumps.

Order of dependency bumps

Step 1: upgrade controller-runtime, controller-tools, helm, and operator-framework/operator-manifest-tools(can be done in parallel)

 - [x] sigs.k8s.io/controller-runtime (https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.18.0)
 - [x]  sigs.k8s.io/controller-tools (https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.15.0)
 - [x]  operator-framework/operator-manifest-tools (https://github.com/operator-framework/operator-manifest-tools/pull/57) (https://github.com/operator-framework/operator-manifest-tools/releases/tag/v0.7.0)

Step 2: upgrade operator-framework/api (can be done immediately after controller-runtime & controller-tools)

- [x]  operator-framework/api (https://github.com/operator-framework/api/pull/322) (https://github.com/operator-framework/api/releases/tag/v0.24.0)

Step 3.1: upgrade operator-framework/operator-registry and operator-framework/operator-lib (can be done immediately after operator-framework/api)

- [x]  operator-framework/operator-registry (https://github.com/operator-framework/operator-registry/pull/1297) (https://github.com/operator-framework/operator-registry/releases/tag/v1.42.0)
- [x]  operator-framework/operator-lib (https://github.com/operator-framework/operator-lib/pull/176) (https://github.com/operator-framework/operator-lib/releases/tag/v0.14.0)

Step 3.2: upgrade kubebuilder

- [x]  sigs.k8s.io/kubebuilder/v4 (https://github.com/kubernetes-sigs/kubebuilder/pull/3912) (https://github.com/kubernetes-sigs/kubebuilder/releases/tag/v4.1.1)

Step 4: upgrade operator-framework plugins

- [x] operator-framework/ansible-operator-plugins (https://github.com/operator-framework/ansible-operator-plugins/pull/102)
- [x]  ~~operator-framework/helm-operator-plugins (https://github.com/operator-framework/helm-operator-plugins/pull/337 & https://github.com/operator-framework/helm-operator-plugins/pull/346)~~
- [x]  ~~operator-framework/java-operator-plugins (https://github.com/operator-framework/java-operator-plugins/pull/151) (https://github.com/operator-framework/java-operator-plugins/releases/tag/v0.11.0)~~

Step 5: upgrade operator-framework/operator-sdk dependencies

- [x]  Bump Ginkgo/v2 and Kubebuilder 1.30
- [x]  Bump SDK to use k8s 1.30

**Comment by Neo2308** [comment]
Copied from https://github.com/operator-framework/operator-sdk/issues/6651
Removed "sigs.k8s.io/kubebuilder-declarative-pattern" based on https://github.com/operator-framework/operator-sdk/issues/6651#issuecomment-1962986659

**Comment by Neo2308** [comment]
K8s 1.30 support for kubebuilder would be coming post the major bump in kubebuilder version. https://github.com/kubernetes-sigs/kubebuilder/discussions/3622

**Comment by acornett21** [comment]
Updated the description to remove the helm operator plugin since we are dropping `hybrid` support

**Comment by Neo2308** [comment]
@acornett21 wouldn't we still need to update the helm operator plugin version in the operator-sdk and hence have to update k8s/controller runtime versions in the helm repo and cut new versions?

**Comment by acornett21** [comment]
@Neo2308 we still need to keep the `helm-operator-plugin` repo up to date (though since other projects depend on that that move at a quicker pace, you probably no longer need to worry about it for your needs), but it no longer needs to be a dependency of this project, since this project still contains the `helm` operator code. Confusing, I know, I assumed all the helm code was in the `plugin` repo, but it is not.

**Comment by acornett21** [comment]
It looks like we'll have to update to kubebuilder v4 for this and use version `4.1.1`, unless I'm missing something.

**Comment by acornett21** [comment]
Released `v1.36.0` of the ansible plugin.

https://github.com/operator-framework/ansible-operator-plugins/releases/tag/v1.36.0

**Comment by acornett21** [comment]
Re-opening as this got auto-closed, items still needed:
- migration docs
- changelog docs

**Comment by arf1372** [comment]
I need this update. When do you think this would happen? Should I use Kubebuilder in the meantime?
I'm using k3s/helm-controller and it depends on controller-runtime 1.30. Hence my code gets broken and I can't develop my operator by now.
Apologies for my limited english. I really need to understand how can I do this?

**Comment by acornett21** [comment]
Release 1.38.0 has been cut

https://github.com/operator-framework/operator-sdk/releases/tag/v1.38.0
