### ISSUE TITLE
Meta:  Important Issues Needing Resolution Before New Release

### ISSUE THREAD

**Issue by acornett21** [operator-framework/operator-sdk#6767]
Below are some of the issues that should be looked at before a release is cut so that the sdk is stable and back to a usable state for all three operator types.

- [x] operator-framework/operator-sdk#6692
- [x] operator-framework/operator-sdk#6698 
- [x] operator-framework/operator-sdk#6690
- [x] operator-framework/operator-sdk#6750
- [ ] operator-framework/operator-sdk#6681 (This has a couple of workarounds, so priority can be lower)
