### ISSUE TITLE
Meta Issue for k8s 1.31 bump

### ISSUE THREAD

**Issue by Neo2308** [operator-framework/operator-sdk#6816]
Meta Issue for k8s 1.31 bump

In order to bump Operator SDK to support Kubernetes 1.31 there are a few dependencies we rely on making the bump first.
This issue is meant to help track all dependencies and the status of their bumps.

Order of dependency bumps

Step 1: upgrade controller-runtime, controller-tools, helm, and operator-framework/operator-manifest-tools(can be done in parallel)

 - [x] sigs.k8s.io/controller-runtime (https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.19.0)
 - [x]  sigs.k8s.io/controller-tools (https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.16.0) (https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.16.1)
 - [x]  operator-framework/operator-manifest-tools (https://github.com/operator-framework/operator-manifest-tools/pull/64)

Step 2: upgrade operator-framework/api (can be done immediately after controller-runtime & controller-tools)

- [x]  operator-framework/api (https://github.com/operator-framework/api/pull/357) (https://github.com/operator-framework/api/releases/tag/v0.27.0)

Step 3.1: upgrade operator-framework/operator-registry and operator-framework/operator-lib (can be done immediately after operator-framework/api)

- [x]  operator-framework/operator-registry (https://github.com/operator-framework/operator-registry/pull/1418) (https://github.com/operator-framework/operator-registry/releases/tag/v1.47.0)
- [x]  operator-framework/operator-lib (https://github.com/operator-framework/operator-lib/pull/192) (https://github.com/operator-framework/operator-lib/releases/tag/v0.15.0)

Step 3.2: upgrade kubebuilder

- [x]  sigs.k8s.io/kubebuilder/v4 (https://github.com/kubernetes-sigs/kubebuilder/pull/4080) (https://github.com/kubernetes-sigs/kubebuilder/releases/tag/v4.2.0)

Step 4: upgrade operator-framework plugins

- [x] operator-framework/ansible-operator-plugins (https://github.com/operator-framework/ansible-operator-plugins/pull/107)

Step 5: upgrade operator-framework/operator-sdk dependencies

- [x]  Bump Ginkgo/v2 and Kubebuilder 1.31
- [x]  Bump SDK to use k8s 1.31

**Comment by Neo2308** [comment]
Copied from https://github.com/operator-framework/operator-sdk/issues/6730
Changed "sigs.k8s.io/kubebuilder/v3" to "sigs.k8s.io/kubebuilder/v4" based on https://github.com/operator-framework/operator-sdk/issues/6730#issuecomment-2123680906

**Comment by acornett21** [comment]
removed helm and java plugin.

**Comment by acornett21** [comment]
This was resolved in the below release
https://github.com/operator-framework/operator-sdk/releases/tag/v1.39.0
